apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: recovery-cluster
spec:
  instances: 2
  storage:
    size: 1Gi

  bootstrap:
    recovery:
      source: cluster-example
      recoveryTarget:
        targetTime: "2025-06-24T08:12:00Z"

  superuserSecret:
    name: appuser-secret

  backup:
    barmanObjectStore:
      destinationPath: s3://pg-backups/
      endpointURL: http://minio.default.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
        maxParallel: 2
        minFlushInterval: 5s
